# Generated by Django 3.0.8 on 2020-08-06 17:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XavierWeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.BigIntegerField()),
                ('omm_code', models.BigIntegerField()),
                ('inmet_code', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('state', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('evapo', models.FloatField(verbose_name='evapotranspiration')),
                ('relHum', models.FloatField(verbose_name='relative humidity')),
                ('solarRad', models.FloatField(verbose_name='solar radiation')),
                ('maxTemp', models.FloatField(verbose_name='maximum temperature')),
                ('minTemp', models.FloatField(verbose_name='minimum temperature')),
                ('windSpeed', models.FloatField(verbose_name='wind speed')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='vismet.XavierWeatherStation')),
            ],
        ),
    ]
