# Generated by Django 3.0.8 on 2020-08-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0002_heatpixel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatPixelTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('preciptation', models.FloatField()),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='vismet.HeatPixel')),
            ],
        ),
    ]
