# Generated by Django 3.0.8 on 2020-08-11 17:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0005_heatpixel_boundings'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.BigIntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('cod_ibge', models.FloatField()),
                ('microestad', models.CharField(max_length=50)),
                ('macroestad', models.CharField(max_length=50)),
                ('fonte', models.CharField(max_length=30)),
                ('data', models.CharField(max_length=50)),
                ('area_km2', models.FloatField()),
                ('perim_m', models.FloatField()),
                ('percen_are', models.FloatField()),
                ('origem', models.CharField(max_length=100)),
                ('regional', models.CharField(max_length=20)),
                ('estrutura', models.CharField(max_length=30)),
                ('esc_local', models.CharField(max_length=30)),
                ('lei_criaca', models.CharField(max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
