# Generated by Django 3.0.8 on 2020-09-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0010_citydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydata',
            name='midTemp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='citydata',
            name='preciptation',
            field=models.FloatField(null=True),
        ),
    ]
