# Generated by Django 3.1.1 on 2020-09-21 17:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0015_auto_20200920_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
