# Generated by Django 3.1.1 on 2020-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0016_auto_20200921_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xavierstationdata',
            name='solarRad',
        ),
        migrations.AddField(
            model_name='xavierstationdata',
            name='solarIns',
            field=models.FloatField(blank=True, null=True, verbose_name='solar insolation'),
        ),
    ]
