# Generated by Django 3.1.1 on 2020-09-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0017_auto_20200925_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='INMETStationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maxTemp', models.FloatField(blank=True, null=True, verbose_name='maximum temperature')),
                ('minTemp', models.FloatField(blank=True, null=True, verbose_name='minimum temperature')),
                ('relHum', models.FloatField(blank=True, null=True, verbose_name='relative humidity')),
                ('precip', models.FloatField(blank=True, null=True, verbose_name='preciptatioin')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmet_data', to='vismet.xavierstation')),
            ],
        ),
    ]
