# Generated by Django 3.1.1 on 2020-09-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0018_inmetstationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmetstationdata',
            name='maxTemp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Máxima'),
        ),
        migrations.AlterField(
            model_name='inmetstationdata',
            name='minTemp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Mínima'),
        ),
        migrations.AlterField(
            model_name='inmetstationdata',
            name='precip',
            field=models.FloatField(blank=True, null=True, verbose_name='Precipitação'),
        ),
        migrations.AlterField(
            model_name='inmetstationdata',
            name='relHum',
            field=models.FloatField(blank=True, null=True, verbose_name='Umidade Relativa'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='evapo',
            field=models.FloatField(blank=True, null=True, verbose_name='Evapotranspiração'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='maxTemp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Máxima'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='minTemp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Mínima'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='relHum',
            field=models.FloatField(blank=True, null=True, verbose_name='Umidade Relativa'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='solarIns',
            field=models.FloatField(blank=True, null=True, verbose_name='Radiação Solar'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='windSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidade do Vento'),
        ),
    ]
