# Generated by Django 3.1.1 on 2020-09-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0019_auto_20200929_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='INMETStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmet_code', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('state', models.CharField(max_length=254)),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Data de início de operação')),
                ('finalDate', models.DateField(blank=True, null=True, verbose_name='Data de   fim de operação')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
