# Generated by Django 3.0.7 on 2020-06-28 22:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationMaxTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('date', models.DateField()),
                ('temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='XavierWeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.BigIntegerField()),
                ('omm_code', models.BigIntegerField()),
                ('inmet_code', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('state', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
