# Generated by Django 3.1.2 on 2020-10-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0003_citydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydata',
            old_name='preciptation',
            new_name='precip',
        ),
    ]
