# Generated by Django 3.0.8 on 2020-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0004_auto_20200806_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatpixel',
            name='boundings',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
