# Generated by Django 3.1.2 on 2020-11-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0004_auto_20201029_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcategory',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da categoria'),
        ),
    ]
