# Generated by Django 3.1.2 on 2020-11-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0005_elementcategory_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsource',
            name='display_name',
            field=models.CharField(default='null', max_length=100, verbose_name='Nome de visualização'),
        ),
    ]
