# Generated by Django 3.1.2 on 2020-11-04 23:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0006_elementsource_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
