# Generated by Django 3.1.2 on 2020-11-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0007_station_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='point',
            new_name='geom',
        ),
    ]
