# Generated by Django 3.1.2 on 2020-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0008_auto_20201104_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcategory',
            name='display_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
