# Generated by Django 3.1.2 on 2020-11-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0010_subsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsource',
            name='related_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsource', to='vismet.elementsource', verbose_name='fonte relacionada'),
        ),
    ]
