# Generated by Django 3.1.2 on 2020-11-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0011_auto_20201110_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsource',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='descrição adicional'),
        ),
    ]
