# Generated by Django 3.0.8 on 2020-09-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0011_auto_20200901_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydata',
            old_name='midTemp',
            new_name='medTemp',
        ),
    ]
