# Generated by Django 3.1.1 on 2020-09-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0012_auto_20200901_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xavierstation',
            name='station_id',
        ),
    ]
