# Generated by Django 3.1.2 on 2020-11-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0012_auto_20201110_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsource',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='subsource',
            name='time_interval',
        ),
        migrations.CreateModel(
            name='SubSourceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=200)),
                ('subsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_subsource', to='vismet.subsource')),
            ],
        ),
    ]
