# Generated by Django 3.1.2 on 2020-11-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0013_auto_20201110_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsource',
            name='related_source',
        ),
        migrations.RemoveField(
            model_name='subsourcedetail',
            name='subsource',
        ),
        migrations.AddField(
            model_name='elementsource',
            name='subsources',
            field=models.ManyToManyField(to='vismet.SubSource'),
        ),
        migrations.AddField(
            model_name='subsource',
            name='details',
            field=models.ManyToManyField(to='vismet.SubSourceDetail'),
        ),
    ]
