# Generated by Django 3.1.1 on 2020-09-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0013_remove_xavierstation_station_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xavierstationdata',
            old_name='station_id',
            new_name='station',
        ),
    ]
