# Generated by Django 3.1.1 on 2020-09-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0014_auto_20200919_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xavierstationdata',
            name='evapo',
            field=models.FloatField(blank=True, null=True, verbose_name='evapotranspiration'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='maxTemp',
            field=models.FloatField(blank=True, null=True, verbose_name='maximum temperature'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='minTemp',
            field=models.FloatField(blank=True, null=True, verbose_name='minimum temperature'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='relHum',
            field=models.FloatField(blank=True, null=True, verbose_name='relative humidity'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='solarRad',
            field=models.FloatField(blank=True, null=True, verbose_name='solar radiation'),
        ),
        migrations.AlterField(
            model_name='xavierstationdata',
            name='windSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='wind speed'),
        ),
    ]
