# Generated by Django 3.1.2 on 2020-11-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0015_auto_20201110_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsource',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
