# Generated by Django 3.1.2 on 2020-11-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0016_subsource_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
    ]
