# Generated by Django 3.1.2 on 2020-11-11 13:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0017_auto_20201111_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='altitude'),
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.CharField(max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='station',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='localização'),
        ),
        migrations.AlterField(
            model_name='station',
            name='inmet_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='código INMET'),
        ),
        migrations.AlterField(
            model_name='station',
            name='omm_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='código OMM'),
        ),
        migrations.AlterField(
            model_name='station',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='vismet.elementsource', verbose_name='fonte'),
        ),
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(max_length=100, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='estado de operação'),
        ),
        migrations.AlterField(
            model_name='station',
            name='type',
            field=models.CharField(max_length=100, verbose_name='tipo'),
        ),
    ]
