# Generated by Django 3.1.2 on 2020-12-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0019_pixeldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixel',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='pixels',
            field=models.ManyToManyField(to='vismet.Pixel'),
        ),
    ]
