# Generated by Django 3.1.1 on 2020-10-02 19:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0020_inmetstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('omm_code', models.CharField(blank=True, max_length=100, null=True)),
                ('inmet_code', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Data de início de operação')),
                ('finalDate', models.DateField(blank=True, null=True, verbose_name='Data de fim de operação')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
