# Generated by Django 3.1.2 on 2020-12-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0020_auto_20201201_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citydata',
            name='medTemp',
        ),
        migrations.AddField(
            model_name='citydata',
            name='data_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='city_data', to='vismet.datamodel'),
        ),
        migrations.AddField(
            model_name='citydata',
            name='evapo',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='maxTemp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='minTemp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='ocis',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='rnof',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='citydata',
            name='tp2m',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='citydata',
            name='precip',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
