# Generated by Django 3.1.2 on 2021-02-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0021_auto_20201201_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityData',
        ),
    ]
