# Generated by Django 3.1.1 on 2020-10-06 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0022_auto_20201006_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementsource',
            name='finalDate',
        ),
        migrations.RemoveField(
            model_name='elementsource',
            name='startDate',
        ),
        migrations.AlterField(
            model_name='elementsource',
            name='variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=20),
        ),
    ]
