# Generated by Django 3.1.2 on 2021-02-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0022_delete_citydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('evapo', models.FloatField(blank=True, default=None, null=True)),
                ('minTemp', models.FloatField(blank=True, default=None, null=True)),
                ('maxTemp', models.FloatField(blank=True, default=None, null=True)),
                ('ocis', models.FloatField(blank=True, default=None, null=True)),
                ('precip', models.FloatField(blank=True, default=None, null=True)),
                ('rnof', models.FloatField(blank=True, default=None, null=True)),
                ('tp2m', models.FloatField(blank=True, default=None, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_data', to='vismet.city')),
                ('data_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='city_data', to='vismet.datamodel')),
            ],
        ),
    ]
