# Generated by Django 3.1.7 on 2021-02-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0023_citydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmetstationdata',
            name='solarIns',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Radiação Solar'),
        ),
    ]
