# Generated by Django 3.1.1 on 2020-10-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0024_auto_20201006_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INMETStation',
        ),
        migrations.AlterField(
            model_name='inmetstationdata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='vismet.weatherstation'),
        ),
    ]
