# Generated by Django 3.1.7 on 2021-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0025_pixel_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixeldata',
            name='relHum',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
