# Generated by Django 3.1.7 on 2021-03-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0026_pixeldata_relhum'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixeldata',
            name='slhf',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pixeldata',
            name='sshf',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pixeldata',
            name='u10',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pixeldata',
            name='v10',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
