# Generated by Django 3.1.2 on 2020-10-26 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0027_anastationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementsource',
            name='variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=2), size=20),
        ),
    ]
