# Generated by Django 3.1.2 on 2020-10-21 13:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0027_anastationdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixel',
            name='boundings',
        ),
        migrations.RemoveField(
            model_name='pixel',
            name='pixel_id',
        ),
        migrations.AddField(
            model_name='pixel',
            name='city',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixel',
            name='state',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pixel',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='pixel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixel_data', to='vismet.pixel'),
        ),
    ]
