# Generated by Django 3.1.7 on 2021-03-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0027_auto_20210311_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixeldata',
            name='evapo',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='evapotranspiração'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='maxTemp',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='temperatura máxima'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='minTemp',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='temperatura mínima'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='ocis',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='radiação de onda curta incidente à superficie'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='precip',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='precipitação'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='relHum',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='umidade relativa do ar'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='rnof',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='escoamento superficial'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='slhf',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='surface latent heat flux'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='sshf',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='surface sensible heat flux'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='tp2m',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='temperatura a 2m'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='u10',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='10m u-component of wind'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='v10',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='10m v-component of wind'),
        ),
    ]
