# Generated by Django 3.1.7 on 2021-03-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0028_auto_20210312_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixeldata',
            name='evapo',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='evapotranspiração (mm)'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='maxTemp',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='temperatura máxima (ºC)'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='minTemp',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='temperatura mínima (ºC)'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='ocis',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='radiação de onda curta incidente à superficie (W/m²)'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='precip',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='precipitação (mm)'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='relHum',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='umidade relativa do ar (%)'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='rnof',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='escoamento superficial (mm)'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='tp2m',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='temperatura a 2m da superfície (ºC)'),
        ),
        migrations.AlterField(
            model_name='pixeldata',
            name='u10',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='10m u-component of wind '),
        ),
    ]
