# Generated by Django 3.1.2 on 2020-10-21 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0028_auto_20201021_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementsource',
            name='variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=20),
        ),
    ]
