# Generated by Django 3.1.7 on 2021-03-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0029_auto_20210312_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixeldata',
            name='time_interval',
            field=models.CharField(default='mensal', max_length=7, verbose_name='intervalo de tempo'),
        ),
    ]
