# Generated by Django 3.1.4 on 2021-03-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0029_auto_20210312_1610'),
        ('vismet', '0029_auto_20210312_1611'),
    ]

    operations = [
    ]
