# Generated by Django 3.1.4 on 2021-03-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0030_pixeldata_time_interval'),
        ('vismet', '0030_merge_20210312_1623'),
    ]

    operations = [
    ]
