# Generated by Django 3.1.2 on 2020-10-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vismet', '0029_auto_20201021_1049'),
        ('vismet', '0030_auto_20201028_1341'),
    ]

    operations = [
    ]
